//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Диплом
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отчеты
    {
        public int КодОтчета { get; set; }
        public Nullable<int> КодСотрудника { get; set; }
        public string НазваниеОтчета { get; set; }
        public Nullable<System.DateTime> ДатаОтчета { get; set; }
        public string СодержаниеОтчета { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
