//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Диплом
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудники()
        {
            this.Отчеты = new HashSet<Отчеты>();
            this.Совещания = new HashSet<Совещания>();
            this.Проекты = new HashSet<Проекты>();
        }
    
        public int КодСотрудника { get; set; }
        public Nullable<int> КодРоли { get; set; }
        public Nullable<int> КодОтдела { get; set; }
        public string ПолноеИмя { get; set; }
        public Nullable<System.DateTime> ДатаПриемаНаРаботу { get; set; }
        public string Пароль { get; set; }
        public string Логин { get; set; }
    
        public virtual Отделы Отделы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Отчеты> Отчеты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Совещания> Совещания { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Проекты> Проекты { get; set; }
    }
}
