//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Диплом
{
    using System;
    using System.Collections.Generic;
    
    public partial class Совещания
    {
        public int КодСовещания { get; set; }
        public Nullable<int> КодCотрудника { get; set; }
        public string НазваниеСовещания { get; set; }
        public Nullable<System.DateTime> ДатаСовещания { get; set; }
        public string Место { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
